[build]
  command = "npm --prefix ./frontend run build"
  publish = "frontend/dist"
  functions = "functions"

[dev]
  command = "npm --prefix ./frontend run dev"
  publish = "frontend/dist"
  functions = "functions"
  framework = "create-react-app"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200