[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "../functions"

[dev]
  
  base = "frontend"
  command = "npm run dev"
  publish = "dist"
  functions = "../functions"
  framework = "create-react-app"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200